version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
        web:
    depends_on:
        - graphite
  graphite:
    image: "graphiteapp/graphite-statsd"
    networks: 
        web:
    restart: always
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
networks:
    web:
